name: CI with Keycloak

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker run -d --name keycloak_unoptimized -p 8080:8080 \
            -e KEYCLOAK_ADMIN=admin \
            -e KEYCLOAK_ADMIN_PASSWORD=change_me \
            -v /path/to/realm/data:/opt/keycloak/data/import \
                quay.io/keycloak/keycloak:20.0.3 \
                start-dev --import-realm

      - name: Make run-tests.sh executable
        run: chmod +x ./run-tests.sh

      - name: Wait for Keycloak to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/ > /dev/null; then
              echo "Keycloak is up!"
              break
            fi
            echo "Waiting for Keycloak to start..."
            sleep 10
          done

      - name: Run tests
        run: ./run-tests.sh
